# run dirs ws-out

In [1]:
! for i in `cat ../Orchestration/junk` ; do echo $i; aws s3 ls ws-out/CONUS/$i ;echo '---------------' ; done

Run02_17_2022/
                           PRE r50t7/
---------------
Run02_24_2022/
                           PRE conus_r50t6/
---------------
Run02_25_2022/
                           PRE conus_r50t5/
                           PRE conus_r50t8/
---------------
Run03_01_2022/
                           PRE conus_r37t0/
---------------
Run03_03_2022/
                           PRE conus_r37t1/
                           PRE conus_r37t2/
---------------
Run03_07_2022/
                           PRE conus_r37t3/
---------------
Run03_11_2022/
                           PRE conus_r50t9/
---------------

# output dirs

In [2]:
! aws s3 ls ws-enduser/CONUS/

                           PRE conus_mos/
                           PRE r37.0_tile0/
                           PRE r37.0_tile1/
                           PRE r37.0_tile2/
                           PRE r37.0_tile3/
                           PRE r50.0_tile5/
                           PRE r50.0_tile6/
                           PRE r50.0_tile7/
                           PRE r50.0_tile8/
                           PRE r50.0_tile9/

In [3]:
import boto3

In [4]:
def s3_bucket_analyze(bucket, prefix):

    objs = []

    print("bucket", bucket)
    print("prefix", prefix)

    bucket_name = bucket
    prefix = prefix

    s3 = boto3.resource('s3')
    bucket = s3.Bucket(bucket_name)
    cnt=0
    storage_class_h = {'STANDARD' : 0,
                   'GLACIER' : 0,
                   'INTELLIGENT_TIERING' : 0,
                  }
    sum_class_h = {'STANDARD' : 0,
                   'GLACIER' : 0,
                   'INTELLIGENT_TIERING' : 0,
                  }
    sum = 0
    for obj in bucket.objects.filter(Prefix=prefix):
        storage_class_h[obj.storage_class] = storage_class_h[obj.storage_class] + 1
        cnt = cnt + 1
        if not cnt%1000:
            print(bucket, "bucket object count = ", cnt, flush=True)
        sum = sum + obj.size
        sum_class_h[obj.storage_class] = sum_class_h[obj.storage_class] + obj.size
        my_obj = {
                'bucket_name':obj.bucket_name,
                'key':obj.key,
                'size':obj.size,
                'class':obj.storage_class
                }
        objs.append(my_obj)

    print ("COUNT=", cnt)
    for ky in storage_class_h.keys():
        print(ky, storage_class_h[ky])
        sum = sum_class_h[ky]
        print(ky, sum_class_h[ky])
        gig = sum/(1024*1024*1024)
        print (ky, "GBYTES=", gig)
        if ky == 'GLACIER': 
            cost=.007
        else: 
            cost=.023
        print (ky, "Cost/Month=", gig * cost)
        print ("----" * 25)
    print("END LOOP")
    my_key = 'STANDARD'
    ret_gbytes = sum_class_h[my_key]/(1024*1024*1024)
    if (ret_gbytes < 1):
        ret_gbytes = 1
    ret_costs = .023 * ret_gbytes
    print('G:', ret_gbytes, ret_costs)
    return objs

In [5]:
bucket='ws-enduser'
my_prefix='CONUS/'

In [6]:
objs = s3_bucket_analyze(bucket, my_prefix)

bucket ws-enduser
prefix CONUS/
s3.Bucket(name='ws-enduser') bucket object count =  1000
s3.Bucket(name='ws-enduser') bucket object count =  2000
s3.Bucket(name='ws-enduser') bucket object count =  3000
s3.Bucket(name='ws-enduser') bucket object count =  4000
s3.Bucket(name='ws-enduser') bucket object count =  5000
s3.Bucket(name='ws-enduser') bucket object count =  6000
s3.Bucket(name='ws-enduser') bucket object count =  7000
s3.Bucket(name='ws-enduser') bucket object count =  8000
s3.Bucket(name='ws-enduser') bucket object count =  9000
s3.Bucket(name='ws-enduser') bucket object count =  10000
s3.Bucket(name='ws-enduser') bucket object count =  11000
s3.Bucket(name='ws-enduser') bucket object count =  12000
s3.Bucket(name='ws-enduser') bucket object count =  13000
s3.Bucket(name='ws-enduser') bucket object count =  14000
s3.Bucket(name='ws-enduser') bucket object count =  15000
s3.Bucket(name='ws-enduser') bucket object count =  16000
s3.Bucket(name='ws-enduser') bucket object count =  17000
s3.Bucket(name='ws-enduser') bucket object count =  18000
s3.Bucket(name='ws-enduser') bucket object count =  19000
s3.Bucket(name='ws-enduser') bucket object count =  20000
s3.Bucket(name='ws-enduser') bucket object count =  21000
s3.Bucket(name='ws-enduser') bucket object count =  22000
s3.Bucket(name='ws-enduser') bucket object count =  23000
s3.Bucket(name='ws-enduser') bucket object count =  24000
s3.Bucket(name='ws-enduser') bucket object count =  25000
s3.Bucket(name='ws-enduser') bucket object count =  26000
s3.Bucket(name='ws-enduser') bucket object count =  27000
s3.Bucket(name='ws-enduser') bucket object count =  28000
s3.Bucket(name='ws-enduser') bucket object count =  29000
s3.Bucket(name='ws-enduser') bucket object count =  30000
s3.Bucket(name='ws-enduser') bucket object count =  31000
s3.Bucket(name='ws-enduser') bucket object count =  32000
s3.Bucket(name='ws-enduser') bucket object count =  33000
s3.Bucket(name='ws-enduser') bucket object count =  34000
s3.Bucket(name='ws-enduser') bucket object count =  35000
s3.Bucket(name='ws-enduser') bucket object count =  36000
s3.Bucket(name='ws-enduser') bucket object count =  37000
s3.Bucket(name='ws-enduser') bucket object count =  38000
s3.Bucket(name='ws-enduser') bucket object count =  39000
s3.Bucket(name='ws-enduser') bucket object count =  40000
s3.Bucket(name='ws-enduser') bucket object count =  41000
s3.Bucket(name='ws-enduser') bucket object count =  42000
s3.Bucket(name='ws-enduser') bucket object count =  43000
s3.Bucket(name='ws-enduser') bucket object count =  44000
s3.Bucket(name='ws-enduser') bucket object count =  45000
s3.Bucket(name='ws-enduser') bucket object count =  46000
s3.Bucket(name='ws-enduser') bucket object count =  47000
s3.Bucket(name='ws-enduser') bucket object count =  48000
s3.Bucket(name='ws-enduser') bucket object count =  49000
s3.Bucket(name='ws-enduser') bucket object count =  50000
s3.Bucket(name='ws-enduser') bucket object count =  51000
s3.Bucket(name='ws-enduser') bucket object count =  52000
s3.Bucket(name='ws-enduser') bucket object count =  53000
s3.Bucket(name='ws-enduser') bucket object count =  54000
s3.Bucket(name='ws-enduser') bucket object count =  55000
s3.Bucket(name='ws-enduser') bucket object count =  56000
s3.Bucket(name='ws-enduser') bucket object count =  57000
s3.Bucket(name='ws-enduser') bucket object count =  58000
s3.Bucket(name='ws-enduser') bucket object count =  59000
s3.Bucket(name='ws-enduser') bucket object count =  60000
s3.Bucket(name='ws-enduser') bucket object count =  61000
s3.Bucket(name='ws-enduser') bucket object count =  62000
s3.Bucket(name='ws-enduser') bucket object count =  63000
s3.Bucket(name='ws-enduser') bucket object count =  64000
s3.Bucket(name='ws-enduser') bucket object count =  65000
s3.Bucket(name='ws-enduser') bucket object count =  66000
s3.Bucket(name='ws-enduser') bucket object count =  67000
s3.Bucket(name='ws-enduser') bucket object count =  68000
s3.Bucket(name='ws-enduser') bucket object count =  69000
s3.Bucket(name='ws-enduser') bucket object count =  70000
s3.Bucket(name='ws-enduser') bucket object count =  71000
s3.Bucket(name='ws-enduser') bucket object count =  72000
s3.Bucket(name='ws-enduser') bucket object count =  73000
s3.Bucket(name='ws-enduser') bucket object count =  74000
s3.Bucket(name='ws-enduser') bucket object count =  75000
s3.Bucket(name='ws-enduser') bucket object count =  76000
s3.Bucket(name='ws-enduser') bucket object count =  77000
s3.Bucket(name='ws-enduser') bucket object count =  78000
s3.Bucket(name='ws-enduser') bucket object count =  79000
s3.Bucket(name='ws-enduser') bucket object count =  80000
s3.Bucket(name='ws-enduser') bucket object count =  81000
s3.Bucket(name='ws-enduser') bucket object count =  82000
s3.Bucket(name='ws-enduser') bucket object count =  83000
s3.Bucket(name='ws-enduser') bucket object count =  84000
s3.Bucket(name='ws-enduser') bucket object count =  85000
s3.Bucket(name='ws-enduser') bucket object count =  86000
s3.Bucket(name='ws-enduser') bucket object count =  87000
s3.Bucket(name='ws-enduser') bucket object count =  88000
s3.Bucket(name='ws-enduser') bucket object count =  89000
s3.Bucket(name='ws-enduser') bucket object count =  90000
s3.Bucket(name='ws-enduser') bucket object count =  91000
s3.Bucket(name='ws-enduser') bucket object count =  92000
s3.Bucket(name='ws-enduser') bucket object count =  93000
s3.Bucket(name='ws-enduser') bucket object count =  94000
s3.Bucket(name='ws-enduser') bucket object count =  95000
s3.Bucket(name='ws-enduser') bucket object count =  96000
s3.Bucket(name='ws-enduser') bucket object count =  97000
s3.Bucket(name='ws-enduser') bucket object count =  98000
s3.Bucket(name='ws-enduser') bucket object count =  99000
s3.Bucket(name='ws-enduser') bucket object count =  100000
s3.Bucket(name='ws-enduser') bucket object count =  101000
s3.Bucket(name='ws-enduser') bucket object count =  102000
s3.Bucket(name='ws-enduser') bucket object count =  103000
s3.Bucket(name='ws-enduser') bucket object count =  104000
s3.Bucket(name='ws-enduser') bucket object count =  105000
s3.Bucket(name='ws-enduser') bucket object count =  106000
s3.Bucket(name='ws-enduser') bucket object count =  107000
s3.Bucket(name='ws-enduser') bucket object count =  108000
s3.Bucket(name='ws-enduser') bucket object count =  109000
s3.Bucket(name='ws-enduser') bucket object count =  110000
s3.Bucket(name='ws-enduser') bucket object count =  111000
s3.Bucket(name='ws-enduser') bucket object count =  112000
s3.Bucket(name='ws-enduser') bucket object count =  113000
s3.Bucket(name='ws-enduser') bucket object count =  114000
s3.Bucket(name='ws-enduser') bucket object count =  115000
s3.Bucket(name='ws-enduser') bucket object count =  116000
s3.Bucket(name='ws-enduser') bucket object count =  117000
s3.Bucket(name='ws-enduser') bucket object count =  118000
s3.Bucket(name='ws-enduser') bucket object count =  119000
s3.Bucket(name='ws-enduser') bucket object count =  120000
s3.Bucket(name='ws-enduser') bucket object count =  121000
s3.Bucket(name='ws-enduser') bucket object count =  122000
s3.Bucket(name='ws-enduser') bucket object count =  123000
s3.Bucket(name='ws-enduser') bucket object count =  124000
s3.Bucket(name='ws-enduser') bucket object count =  125000
s3.Bucket(name='ws-enduser') bucket object count =  126000
s3.Bucket(name='ws-enduser') bucket object count =  127000
s3.Bucket(name='ws-enduser') bucket object count =  128000
s3.Bucket(name='ws-enduser') bucket object count =  129000
s3.Bucket(name='ws-enduser') bucket object count =  130000
s3.Bucket(name='ws-enduser') bucket object count =  131000
s3.Bucket(name='ws-enduser') bucket object count =  132000
s3.Bucket(name='ws-enduser') bucket object count =  133000
s3.Bucket(name='ws-enduser') bucket object count =  134000
s3.Bucket(name='ws-enduser') bucket object count =  135000
s3.Bucket(name='ws-enduser') bucket object count =  136000
s3.Bucket(name='ws-enduser') bucket object count =  137000
s3.Bucket(name='ws-enduser') bucket object count =  138000
s3.Bucket(name='ws-enduser') bucket object count =  139000
s3.Bucket(name='ws-enduser') bucket object count =  140000
s3.Bucket(name='ws-enduser') bucket object count =  141000

s3.Bucket(name='ws-enduser') bucket object count =  142000
s3.Bucket(name='ws-enduser') bucket object count =  143000
s3.Bucket(name='ws-enduser') bucket object count =  144000
s3.Bucket(name='ws-enduser') bucket object count =  145000
s3.Bucket(name='ws-enduser') bucket object count =  146000
s3.Bucket(name='ws-enduser') bucket object count =  147000
s3.Bucket(name='ws-enduser') bucket object count =  148000
s3.Bucket(name='ws-enduser') bucket object count =  149000
s3.Bucket(name='ws-enduser') bucket object count =  150000
s3.Bucket(name='ws-enduser') bucket object count =  151000
s3.Bucket(name='ws-enduser') bucket object count =  152000
s3.Bucket(name='ws-enduser') bucket object count =  153000
s3.Bucket(name='ws-enduser') bucket object count =  154000
s3.Bucket(name='ws-enduser') bucket object count =  155000
s3.Bucket(name='ws-enduser') bucket object count =  156000
s3.Bucket(name='ws-enduser') bucket object count =  157000
s3.Bucket(name='ws-enduser') bucket object count =  158000
s3.Bucket(name='ws-enduser') bucket object count =  159000
s3.Bucket(name='ws-enduser') bucket object count =  160000
s3.Bucket(name='ws-enduser') bucket object count =  161000
s3.Bucket(name='ws-enduser') bucket object count =  162000
s3.Bucket(name='ws-enduser') bucket object count =  163000
s3.Bucket(name='ws-enduser') bucket object count =  164000
s3.Bucket(name='ws-enduser') bucket object count =  165000
s3.Bucket(name='ws-enduser') bucket object count =  166000
s3.Bucket(name='ws-enduser') bucket object count =  167000
s3.Bucket(name='ws-enduser') bucket object count =  168000
s3.Bucket(name='ws-enduser') bucket object count =  169000
s3.Bucket(name='ws-enduser') bucket object count =  170000
s3.Bucket(name='ws-enduser') bucket object count =  171000
s3.Bucket(name='ws-enduser') bucket object count =  172000
s3.Bucket(name='ws-enduser') bucket object count =  173000
s3.Bucket(name='ws-enduser') bucket object count =  174000
s3.Bucket(name='ws-enduser') bucket object count =  175000
s3.Bucket(name='ws-enduser') bucket object count =  176000
s3.Bucket(name='ws-enduser') bucket object count =  177000
s3.Bucket(name='ws-enduser') bucket object count =  178000
s3.Bucket(name='ws-enduser') bucket object count =  179000
s3.Bucket(name='ws-enduser') bucket object count =  180000
s3.Bucket(name='ws-enduser') bucket object count =  181000
s3.Bucket(name='ws-enduser') bucket object count =  182000
s3.Bucket(name='ws-enduser') bucket object count =  183000
s3.Bucket(name='ws-enduser') bucket object count =  184000
s3.Bucket(name='ws-enduser') bucket object count =  185000
s3.Bucket(name='ws-enduser') bucket object count =  186000
s3.Bucket(name='ws-enduser') bucket object count =  187000
s3.Bucket(name='ws-enduser') bucket object count =  188000
s3.Bucket(name='ws-enduser') bucket object count =  189000
s3.Bucket(name='ws-enduser') bucket object count =  190000
s3.Bucket(name='ws-enduser') bucket object count =  191000
s3.Bucket(name='ws-enduser') bucket object count =  192000
s3.Bucket(name='ws-enduser') bucket object count =  193000
s3.Bucket(name='ws-enduser') bucket object count =  194000
s3.Bucket(name='ws-enduser') bucket object count =  195000
s3.Bucket(name='ws-enduser') bucket object count =  196000
s3.Bucket(name='ws-enduser') bucket object count =  197000
s3.Bucket(name='ws-enduser') bucket object count =  198000
s3.Bucket(name='ws-enduser') bucket object count =  199000
s3.Bucket(name='ws-enduser') bucket object count =  200000
s3.Bucket(name='ws-enduser') bucket object count =  201000
s3.Bucket(name='ws-enduser') bucket object count =  202000
s3.Bucket(name='ws-enduser') bucket object count =  203000
s3.Bucket(name='ws-enduser') bucket object count =  204000
s3.Bucket(name='ws-enduser') bucket object count =  205000
s3.Bucket(name='ws-enduser') bucket object count =  206000
s3.Bucket(name='ws-enduser') bucket object count =  207000
s3.Bucket(name='ws-enduser') bucket object count =  208000
s3.Bucket(name='ws-enduser') bucket object count =  209000
s3.Bucket(name='ws-enduser') bucket object count =  210000
s3.Bucket(name='ws-enduser') bucket object count =  211000
s3.Bucket(name='ws-enduser') bucket object count =  212000
s3.Bucket(name='ws-enduser') bucket object count =  213000
s3.Bucket(name='ws-enduser') bucket object count =  214000
s3.Bucket(name='ws-enduser') bucket object count =  215000
s3.Bucket(name='ws-enduser') bucket object count =  216000
s3.Bucket(name='ws-enduser') bucket object count =  217000
s3.Bucket(name='ws-enduser') bucket object count =  218000
s3.Bucket(name='ws-enduser') bucket object count =  219000
s3.Bucket(name='ws-enduser') bucket object count =  220000
s3.Bucket(name='ws-enduser') bucket object count =  221000
s3.Bucket(name='ws-enduser') bucket object count =  222000
s3.Bucket(name='ws-enduser') bucket object count =  223000
s3.Bucket(name='ws-enduser') bucket object count =  224000
s3.Bucket(name='ws-enduser') bucket object count =  225000
s3.Bucket(name='ws-enduser') bucket object count =  226000
s3.Bucket(name='ws-enduser') bucket object count =  227000
s3.Bucket(name='ws-enduser') bucket object count =  228000
s3.Bucket(name='ws-enduser') bucket object count =  229000
s3.Bucket(name='ws-enduser') bucket object count =  230000
s3.Bucket(name='ws-enduser') bucket object count =  231000
s3.Bucket(name='ws-enduser') bucket object count =  232000
s3.Bucket(name='ws-enduser') bucket object count =  233000
s3.Bucket(name='ws-enduser') bucket object count =  234000
s3.Bucket(name='ws-enduser') bucket object count =  235000
s3.Bucket(name='ws-enduser') bucket object count =  236000
s3.Bucket(name='ws-enduser') bucket object count =  237000
s3.Bucket(name='ws-enduser') bucket object count =  238000
s3.Bucket(name='ws-enduser') bucket object count =  239000
s3.Bucket(name='ws-enduser') bucket object count =  240000
s3.Bucket(name='ws-enduser') bucket object count =  241000
s3.Bucket(name='ws-enduser') bucket object count =  242000
s3.Bucket(name='ws-enduser') bucket object count =  243000
s3.Bucket(name='ws-enduser') bucket object count =  244000
s3.Bucket(name='ws-enduser') bucket object count =  245000
s3.Bucket(name='ws-enduser') bucket object count =  246000
s3.Bucket(name='ws-enduser') bucket object count =  247000
s3.Bucket(name='ws-enduser') bucket object count =  248000
s3.Bucket(name='ws-enduser') bucket object count =  249000
s3.Bucket(name='ws-enduser') bucket object count =  250000
s3.Bucket(name='ws-enduser') bucket object count =  251000
s3.Bucket(name='ws-enduser') bucket object count =  252000
s3.Bucket(name='ws-enduser') bucket object count =  253000
s3.Bucket(name='ws-enduser') bucket object count =  254000
s3.Bucket(name='ws-enduser') bucket object count =  255000
s3.Bucket(name='ws-enduser') bucket object count =  256000
s3.Bucket(name='ws-enduser') bucket object count =  257000
s3.Bucket(name='ws-enduser') bucket object count =  258000
s3.Bucket(name='ws-enduser') bucket object count =  259000
s3.Bucket(name='ws-enduser') bucket object count =  260000
s3.Bucket(name='ws-enduser') bucket object count =  261000
s3.Bucket(name='ws-enduser') bucket object count =  262000
s3.Bucket(name='ws-enduser') bucket object count =  263000
s3.Bucket(name='ws-enduser') bucket object count =  264000
s3.Bucket(name='ws-enduser') bucket object count =  265000
s3.Bucket(name='ws-enduser') bucket object count =  266000
s3.Bucket(name='ws-enduser') bucket object count =  267000
s3.Bucket(name='ws-enduser') bucket object count =  268000
s3.Bucket(name='ws-enduser') bucket object count =  269000
s3.Bucket(name='ws-enduser') bucket object count =  270000
s3.Bucket(name='ws-enduser') bucket object count =  271000
s3.Bucket(name='ws-enduser') bucket object count =  272000
s3.Bucket(name='ws-enduser') bucket object count =  273000
s3.Bucket(name='ws-enduser') bucket object count =  274000
s3.Bucket(name='ws-enduser') bucket object count =  275000
s3.Bucket(name='ws-enduser') bucket object count =  276000
s3.Bucket(name='ws-enduser') bucket object count =  277000
s3.Bucket(name='ws-enduser') bucket object count =  278000
s3.Bucket(name='ws-enduser') bucket object count =  279000
s3.Bucket(name='ws-enduser') bucket object count =  280000

s3.Bucket(name='ws-enduser') bucket object count =  281000
s3.Bucket(name='ws-enduser') bucket object count =  282000
s3.Bucket(name='ws-enduser') bucket object count =  283000
s3.Bucket(name='ws-enduser') bucket object count =  284000
s3.Bucket(name='ws-enduser') bucket object count =  285000
s3.Bucket(name='ws-enduser') bucket object count =  286000
s3.Bucket(name='ws-enduser') bucket object count =  287000
s3.Bucket(name='ws-enduser') bucket object count =  288000
s3.Bucket(name='ws-enduser') bucket object count =  289000
s3.Bucket(name='ws-enduser') bucket object count =  290000
s3.Bucket(name='ws-enduser') bucket object count =  291000
s3.Bucket(name='ws-enduser') bucket object count =  292000
s3.Bucket(name='ws-enduser') bucket object count =  293000
s3.Bucket(name='ws-enduser') bucket object count =  294000
s3.Bucket(name='ws-enduser') bucket object count =  295000
s3.Bucket(name='ws-enduser') bucket object count =  296000
s3.Bucket(name='ws-enduser') bucket object count =  297000
s3.Bucket(name='ws-enduser') bucket object count =  298000
s3.Bucket(name='ws-enduser') bucket object count =  299000
s3.Bucket(name='ws-enduser') bucket object count =  300000
s3.Bucket(name='ws-enduser') bucket object count =  301000
s3.Bucket(name='ws-enduser') bucket object count =  302000
s3.Bucket(name='ws-enduser') bucket object count =  303000
s3.Bucket(name='ws-enduser') bucket object count =  304000
s3.Bucket(name='ws-enduser') bucket object count =  305000
s3.Bucket(name='ws-enduser') bucket object count =  306000
s3.Bucket(name='ws-enduser') bucket object count =  307000
s3.Bucket(name='ws-enduser') bucket object count =  308000
s3.Bucket(name='ws-enduser') bucket object count =  309000
s3.Bucket(name='ws-enduser') bucket object count =  310000
s3.Bucket(name='ws-enduser') bucket object count =  311000
s3.Bucket(name='ws-enduser') bucket object count =  312000
s3.Bucket(name='ws-enduser') bucket object count =  313000
s3.Bucket(name='ws-enduser') bucket object count =  314000
s3.Bucket(name='ws-enduser') bucket object count =  315000
s3.Bucket(name='ws-enduser') bucket object count =  316000
s3.Bucket(name='ws-enduser') bucket object count =  317000
s3.Bucket(name='ws-enduser') bucket object count =  318000
s3.Bucket(name='ws-enduser') bucket object count =  319000
s3.Bucket(name='ws-enduser') bucket object count =  320000
s3.Bucket(name='ws-enduser') bucket object count =  321000
s3.Bucket(name='ws-enduser') bucket object count =  322000
s3.Bucket(name='ws-enduser') bucket object count =  323000
s3.Bucket(name='ws-enduser') bucket object count =  324000
s3.Bucket(name='ws-enduser') bucket object count =  325000
s3.Bucket(name='ws-enduser') bucket object count =  326000
s3.Bucket(name='ws-enduser') bucket object count =  327000
s3.Bucket(name='ws-enduser') bucket object count =  328000
s3.Bucket(name='ws-enduser') bucket object count =  329000
s3.Bucket(name='ws-enduser') bucket object count =  330000
s3.Bucket(name='ws-enduser') bucket object count =  331000
s3.Bucket(name='ws-enduser') bucket object count =  332000
s3.Bucket(name='ws-enduser') bucket object count =  333000
s3.Bucket(name='ws-enduser') bucket object count =  334000
s3.Bucket(name='ws-enduser') bucket object count =  335000
s3.Bucket(name='ws-enduser') bucket object count =  336000
s3.Bucket(name='ws-enduser') bucket object count =  337000
s3.Bucket(name='ws-enduser') bucket object count =  338000
s3.Bucket(name='ws-enduser') bucket object count =  339000
s3.Bucket(name='ws-enduser') bucket object count =  340000
s3.Bucket(name='ws-enduser') bucket object count =  341000
s3.Bucket(name='ws-enduser') bucket object count =  342000
s3.Bucket(name='ws-enduser') bucket object count =  343000
s3.Bucket(name='ws-enduser') bucket object count =  344000
s3.Bucket(name='ws-enduser') bucket object count =  345000
s3.Bucket(name='ws-enduser') bucket object count =  346000
s3.Bucket(name='ws-enduser') bucket object count =  347000
s3.Bucket(name='ws-enduser') bucket object count =  348000
s3.Bucket(name='ws-enduser') bucket object count =  349000
s3.Bucket(name='ws-enduser') bucket object count =  350000
s3.Bucket(name='ws-enduser') bucket object count =  351000
s3.Bucket(name='ws-enduser') bucket object count =  352000
s3.Bucket(name='ws-enduser') bucket object count =  353000
s3.Bucket(name='ws-enduser') bucket object count =  354000
s3.Bucket(name='ws-enduser') bucket object count =  355000
s3.Bucket(name='ws-enduser') bucket object count =  356000
s3.Bucket(name='ws-enduser') bucket object count =  357000
s3.Bucket(name='ws-enduser') bucket object count =  358000
s3.Bucket(name='ws-enduser') bucket object count =  359000
s3.Bucket(name='ws-enduser') bucket object count =  360000
s3.Bucket(name='ws-enduser') bucket object count =  361000
s3.Bucket(name='ws-enduser') bucket object count =  362000
s3.Bucket(name='ws-enduser') bucket object count =  363000
s3.Bucket(name='ws-enduser') bucket object count =  364000
s3.Bucket(name='ws-enduser') bucket object count =  365000
s3.Bucket(name='ws-enduser') bucket object count =  366000
s3.Bucket(name='ws-enduser') bucket object count =  367000
s3.Bucket(name='ws-enduser') bucket object count =  368000
s3.Bucket(name='ws-enduser') bucket object count =  369000
s3.Bucket(name='ws-enduser') bucket object count =  370000
s3.Bucket(name='ws-enduser') bucket object count =  371000
s3.Bucket(name='ws-enduser') bucket object count =  372000
s3.Bucket(name='ws-enduser') bucket object count =  373000
s3.Bucket(name='ws-enduser') bucket object count =  374000
s3.Bucket(name='ws-enduser') bucket object count =  375000
s3.Bucket(name='ws-enduser') bucket object count =  376000
s3.Bucket(name='ws-enduser') bucket object count =  377000
COUNT= 377609
STANDARD 377609
STANDARD 37177380938572
STANDARD GBYTES= 34624.13413317129
STANDARD Cost/Month= 796.3550850629397
----------------------------------------------------------------------------------------------------
GLACIER 0
GLACIER 0
GLACIER GBYTES= 0.0
GLACIER Cost/Month= 0.0
----------------------------------------------------------------------------------------------------
INTELLIGENT_TIERING 0
INTELLIGENT_TIERING 0
INTELLIGENT_TIERING GBYTES= 0.0
INTELLIGENT_TIERING Cost/Month= 0.0
----------------------------------------------------------------------------------------------------
END LOOP
G: 34624.13413317129 796.3550850629397

In [7]:
objs[405]

{'bucket_name': 'ws-enduser',
 'key': 'CONUS/r37.0_tile0/2000/dd_2000190.tif',
 'size': 951304,
 'class': 'STANDARD'}

In [8]:
new_objs=[]
for o in objs:
    a = o['key'].split('/')
    project = a[0]
    tile = a[1]
    year = a[2]
    basenm = a[3]
    new_o = {
        'bucket_name': o['bucket_name'],
        'project': project,
        'tile': tile,
        'year': year,
        'basename': basenm,
        'size': o['size']
    }
    new_objs.append(new_o)

In [9]:
import pandas as pd

df = pd.DataFrame(new_objs)

In [10]:
df

       bucket_name project         tile  year          basename        size
0       ws-enduser   CONUS    conus_mos  2000  etasw_200001.tif  1596706187
1       ws-enduser   CONUS    conus_mos  2000  etasw_200002.tif  1634386411
2       ws-enduser   CONUS    conus_mos  2000  etasw_200003.tif  1648461792
3       ws-enduser   CONUS    conus_mos  2000  etasw_200004.tif  1646139536
4       ws-enduser   CONUS    conus_mos  2000  etasw_200005.tif  1652544513
...            ...     ...          ...   ...               ...         ...
377604  ws-enduser   CONUS  r50.0_tile9  2020   srf_2020362.tif      928451
377605  ws-enduser   CONUS  r50.0_tile9  2020   srf_2020363.tif     2375655
377606  ws-enduser   CONUS  r50.0_tile9  2020   srf_2020364.tif      928451
377607  ws-enduser   CONUS  r50.0_tile9  2020   srf_2020365.tif      938905
377608  ws-enduser   CONUS  r50.0_tile9  2020   srf_2020366.tif      938799

[377609 rows x 6 columns]

In [11]:
tiles = df['tile'].unique()

In [12]:
tiles

array(['conus_mos', 'r37.0_tile0', 'r37.0_tile1', 'r37.0_tile2',
       'r37.0_tile3', 'r50.0_tile5', 'r50.0_tile6', 'r50.0_tile7',
       'r50.0_tile8', 'r50.0_tile9'], dtype=object)

In [13]:
tdf = df[df['tile'] == tiles[0]]

In [14]:
tdf

    bucket_name project       tile  year          basename        size
0    ws-enduser   CONUS  conus_mos  2000  etasw_200001.tif  1596706187
1    ws-enduser   CONUS  conus_mos  2000  etasw_200002.tif  1634386411
2    ws-enduser   CONUS  conus_mos  2000  etasw_200003.tif  1648461792
3    ws-enduser   CONUS  conus_mos  2000  etasw_200004.tif  1646139536
4    ws-enduser   CONUS  conus_mos  2000  etasw_200005.tif  1652544513
..          ...     ...        ...   ...               ...         ...
139  ws-enduser   CONUS  conus_mos  2011  etasw_201109.tif  1649743262
140  ws-enduser   CONUS  conus_mos  2011  etasw_201110.tif  1650184632
141  ws-enduser   CONUS  conus_mos  2011  etasw_201111.tif  1651359650
142  ws-enduser   CONUS  conus_mos  2011  etasw_201112.tif  1660090594
143  ws-enduser   CONUS  conus_mos  2012  etasw_201201.tif  1593942066

[144 rows x 6 columns]

In [15]:
tdf.describe()

               size
count  1.440000e+02
mean   1.644133e+09
std    1.689830e+07
min    1.593045e+09
25%    1.645585e+09
50%    1.648880e+09
75%    1.651801e+09
max    1.664669e+09

In [16]:
variables = ['etasw','srf', 'dd','netet', 'etc']
#variables = ['etasw']

start_year=2000
end_year=2000

In [17]:
import re
work_sums=[]
def validate_monthly_data(tdf, tile):
    global work_sums
    total_work_left = 0
    records = []
    for variable in variables:
        for year in range(2000,2020+1):
            ytdf = tdf[tdf['year'] == str(year)]
            basenames = ytdf['basename'].to_list()
            rematch=f'{variable}_{year}\d\d\d.tif'
            r = re.compile(rematch)
            my_monthly_list_by_var = [x for x in basenames if r.match(x)]
            my_len = len(my_monthly_list_by_var)
            if my_len < 365:
                total_work_left = total_work_left + 365 - my_len
                o={
                    'tile': tile,
                    'variable': variable,
                    'year': year,
                    'completed:': len(my_monthly_list_by_var)
                }
                print(o)
                records.append(o)
    my_work=f'{tile}: work remaining: {total_work_left}'
    work_sums.append(my_work)
    print(my_work)
    return records

In [18]:
tiles

array(['conus_mos', 'r37.0_tile0', 'r37.0_tile1', 'r37.0_tile2',
       'r37.0_tile3', 'r50.0_tile5', 'r50.0_tile6', 'r50.0_tile7',
       'r50.0_tile8', 'r50.0_tile9'], dtype=object)

In [19]:
for tile in tiles[1:10]:
    tdf = df[df['tile'] == tile]
    records = validate_monthly_data(tdf, tile)
    #print(tile, total_work_left)

r37.0_tile0: work remaining: 0
r37.0_tile1: work remaining: 0
r37.0_tile2: work remaining: 0
r37.0_tile3: work remaining: 0
r50.0_tile5: work remaining: 0
r50.0_tile6: work remaining: 0
r50.0_tile7: work remaining: 0
r50.0_tile8: work remaining: 0
r50.0_tile9: work remaining: 0

In [20]:
#! aws s3 rm --recur  s3://ws-enduser/CONUS/r37.0_tile/

In [21]:
work_sums

['r37.0_tile0: work remaining: 0',
 'r37.0_tile1: work remaining: 0',
 'r37.0_tile2: work remaining: 0',
 'r37.0_tile3: work remaining: 0',
 'r50.0_tile5: work remaining: 0',
 'r50.0_tile6: work remaining: 0',
 'r50.0_tile7: work remaining: 0',
 'r50.0_tile8: work remaining: 0',
 'r50.0_tile9: work remaining: 0']